<?php
// $Id$
/**
 * @file
 * fastwebfeed_aggregator.install
 * 
 * This a ".install"-file. 
 * 
 * @author Jo Bollen <fastwebfeed@gmail.com>
 * @site http://cupid-project.be/project/fastwebfeed-module
 * @filesource
 */

 /**
 * Implementation of hook_install().
 */
function fastwebfeed_aggregator_install() {
  drupal_set_message(t('Installation of the fastwebfeed_aggregator.module started.'));
  // admin settings
  variable_set('fastwebfeed_aggregator_check_ping_on_cron_admin', '1');
  variable_set('fastwebfeed_aggregator_check_aggregator_feed_admin', '1');
  variable_set('fastwebfeed_aggregator_check_category_all_admin', '1');
  // system weight of the module
  db_query("UPDATE {system} SET weight = 10 WHERE name = 'fastwebfeed_aggregator'");
  drupal_set_message(t('Installation of the fastwebfeed_aggregator.module completed.'));
}

/**
 * Implementation of hook_uninstall().
 */
function fastwebfeed_aggregator_uninstall() {
  variable_del('fastwebfeed_aggregator_check_ping_on_cron_admin');
  variable_del('fastwebfeed_aggregator_check_aggregator_feed_admin');
  variable_del('fastwebfeed_aggregator_feed_paths');
  variable_del('fastwebfeed_aggregator_check_category_all_admin');
  variable_del('fastwebfeed_aggregator_check_category_some_admin');
  variable_del('fastwebfeed_aggregator_select_category_admin');
}